apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-blog
  template:
    metadata:
      labels:
        app: simple-blog
    spec:
      containers:
        - name: simple-blog
          image: simple-devops-blog:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
